#:kivy 1.0.9

<ChessCell>:
    set_hint: None, None
    on_release: self.parent.parent.parent.chesscell_clicked(self.id)
    Image:
        set_hint: None, None
        allow_stretch: True
        keep_ratio: False
        y: self.parent.y - (self.parent.height - self.height)/2
        x: self.parent.x
        height: self.parent.height
        width: self.parent.width

<ChessGame>:
    ChessBoard:
        id: chess_board
        cols: 8
        rows: 8
